version: '3.9'

services:
  docking:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - app_storage:/var/www/html/storage/app
    links:
      - gotenberg
    ports:
      - '8888:80'

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - '9898:3000'

volumes:
  app_storage:
