version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  # this will start: php-fpm and worker (using supervisor)
  php:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - app_storage:/var/www/html/storage/app

volumes:
  app_storage:
