version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    links:
      - php

  php:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - app_storage:/var/www/html/storage/app

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - '9898:3000'

volumes:
  app_storage:
