name: Push Docker Dev Image
env:
  DEV_IMAGE_ENV: ${{ secrets.DEV_IMAGE_ENV }}
  IMAGE: 'shipsaas/docking-dev'

on:
  push:
    tags:
      - v1.*

jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
          if: success()

      -   name: Setup
          if: success()
          run: |
            sudo service mysql start
            php -v
            mysql -uroot -proot -e "CREATE DATABASE docking;"
            composer install --no-interaction
            echo "$DEV_IMAGE_ENV" > .env
            touch docking.sqlite
            php artisan key:generate

      -   name: Build Image
          if: success()
          run: |
            docker build -f .docker/Dockerfile \
              -t ${IMAGE}:${GITHUB_REF_NAME} \
              -t ${IMAGE}:latest
